-- Create chat_history table
create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  session_id text not null,
  role text not null,
  content text not null,
  thinking_time float,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster queries by session
create index if not exists idx_chat_history_session_id on chat_history(session_id);

-- Enable Row Level Security
alter table chat_history enable row level security;

-- Create Policies
-- Allow anonymous access (read/write) for development/demo purposes
-- In production, you likely want to restrict this based on user_id
create policy "Enable read access for all users" on chat_history for select using (true);
create policy "Enable insert access for all users" on chat_history for insert with check (true);
create policy "Enable delete access for all users" on chat_history for delete using (true);
create policy "Enable update access for all users" on chat_history for update using (true);
